general:
  name: #{GENERAL_NAME}#

db:
  host: #{DB_HOST}#
  port: #{DB_PORT}#
  username: #{DB_USERNAME}#
  password: #{DB_PASSWORD]}#
  database: #{DB_DATABASE}#

telegram:
  token: #{TELEGRAM_TOKEN}#
